### PR TITLE
Alog: Bug Fix

### LINKED ISSUE #233: Logger: Bug involving Modified Duplicates
This was a bug from PE-D that was resolved:
#166 by updating the UG to mention that the logger works as a snapshot so editing the patient should not edit the log.

However, there is a potential bug that is partially related to it.

Assume we have a patient John A.

Steps to reproduce:
1. Do a `find/A` and `log`.
2. We do a valid edit command on John A i.e. `edit n/John A <fields>`
3. We then do `alog` with the new John A after doing a `find/A`. 
4. An error: `Person(s) already in list is outputted.`

From the UG I am aware that this was mentioned:
> Duplicate patients will not be appended to the log.

But then I am not really sure if this is a bug. Should there be an updating of the log happening instead?

### PR DESCRIPTION
**Pull request by kanna-1**
Resolves #233

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/AppendLogCommand.java [hunk 1]
```diff
@@ -51,22 +53,31 @@ public CommandResult execute(Model model) throws CommandException {
...
-
         boolean hasDupes = false;
         String duplicateClause = "";
+
         for (Person person : model.getFoundPersonsList()) {
-            if (model.getLogBook().hasPerson(person)) {
+            if (!model.getLogBook().hasPerson(person)) {
+                model.getLogBook().addPerson(person);
+                continue;
+            }
```
Comment (WZWren) [inline src/main/java/seedu/address/logic/commands/AppendLogCommand.java:63]: Nice work ensuring a low level of nesting!

**Review by WZWren — COMMENTED** [review]
This looks good!
